# --- DB config (we'll refine later) ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/maintenance
quarkus.datasource.username=maintuser
quarkus.datasource.password=maintpass

# jOOQ dialect
quarkus.jooq.dialect=POSTGRES

# Disable Dev Services for Keycloak for now (no auto Keycloak container)
quarkus.keycloak.devservices.enabled=false

# Also completely disable OIDC until we configure it
quarkus.oidc.enabled=false
